name: "Lint Python code"
on:
  push: # Only execute on push events on the main branch
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint: # Job's name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Specify the Python version to use
          cache: 'pip'
      - name: install dependencies
        run: python -m pip install ruff
      - name: Lint the code
        run: ruff check --output-format=github